version: "3"

services:
  localstack:
    container_name: "localstack_main"
    image: localstack/localstack
    ports:
      - "4567-4599:4567-4599"
      - "9090:9090"
    environment:
      - PORT_WEB_UI=9090
      - LAMBDA_EXECUTOR=docker
      - LAMBDA_REMOTE_DOCKER=0
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"