version: "3"

services:
  sqs-reader:
    build: SqsReader/src/SqsReader
    ports:
      - 5200:5200
    environment:
      - LocalstackHostname=host.docker.internal
      - AwsQueueName
      - AwsQueueIsFifo
      - AwsQueueLongPollTimeSeconds
      - AwsQueueAutomaticallyCreate

  sqs-writer:
    build: SqsWriter/src/SqsWriter
    ports:
      - 5100:5100
    environment:
      - LocalstackHostname=host.docker.internal
      - AwsQueueName
      - AwsQueueIsFifo
      - AwsQueueLongPollTimeSeconds
      - AwsQueueAutomaticallyCreate