service: DynamoDbServerless

provider:
  name: aws
  runtime: dotnetcore2.1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
      Resource: ${env:actorsTableArn}

package:
  individually: true

functions:
  actors:
    handler: CsharpHandlers::DynamoDbServerless.ActorsHandler::QueryActors
    events:
      - http:
          path: actors/search
          method: post

    package:
      artifact: bin/release/netcoreapp2.1/DynamoDbServerless.zip